import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navigation from '@/components/navigation';
import Footer from '@/components/footer';
import {
  getStrapiData,
  globalSettingsQuery,
} from '@/utils/strapi-url';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Async function to fetch global settings
async function fetchGlobalSettings() {
  const data = await getStrapiData(
    'api/global-setting',
    globalSettingsQuery
  );
  return data?.data?.attributes || {};
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch the global settings data
  const globalSettings = await fetchGlobalSettings();

  const navigationLinks = [
    {
      name: 'Home',
      link: '/',
    },
    {
      name: 'About',
      link: '/about',
    },
    // You can include more links dynamically if needed
  ];

  console.log(globalSettings.socialMediaHandles);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased lg:max-w-7xl mx-auto`}
      >
        {/* Pass globalSettings to Navigation and Footer */}
        <Navigation
          navigation={navigationLinks}
          logo={globalSettings.logo}
        />
        {children}
        <Footer
          logo={globalSettings.logo}
          navigation={navigationLinks}
          socials={globalSettings.socialMediaHandles}
        />
      </body>
    </html>
  );
}
