import type { Metadata } from 'next';
import './globals.css';
import Navigation from '@/components/navigation';
import Footer from '@/components/footer';
import {
  getStrapiData,
  globalSettingsQuery,
} from '@/utils/strapi-url';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Async function to fetch global settings
async function fetchGlobalSettings() {
  const data = await getStrapiData(
    'api/global-setting',
    globalSettingsQuery
  );
  return data?.data?.attributes || {};
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch the global settings data
  const globalSettings = await fetchGlobalSettings();

  const navigationLinks = [
    {
      name: 'Home',
      href: '/',
    },
    {
      name: 'Menu',
      href: '/menu',
    },
    {
      name: 'About',
      href: '/facts-and-questions',
    },
  ];

  return (
    <html lang="en">
      <body className={` antialiased lg:max-w-7xl mx-auto`}>
        {/* Pass globalSettings to Navigation and Footer */}
        <Navigation
          navigation={navigationLinks}
          logo={globalSettings.logo?.data?.attributes}
        />
        {children}
        <Footer
          logo={globalSettings.logo}
          navigation={navigationLinks}
          socials={globalSettings.socialMediaHandles}
        />
      </body>
    </html>
  );
}
